const chinese: Record<string, string> = {
  'Work context': '查看作品上下文',
  'Original work': '打开原作',
  'How can I help you today?': '今天想一起做什么？',
  'Loading conversation': '正在读取会话',
  'Scroll to bottom': '滚动到底部',
  'Send a message...': '发送给本地 Agent…',
  'Message input': '发送给本地 Agent',
  'Send message': '发送',
  'Stop generating': '停止',
  Copy: '复制',
  Refresh: '重新生成',
  More: '更多',
  'Export as Markdown': '导出为 Markdown',
  Edit: '编辑',
  Previous: '上一条',
  Next: '下一条',
  Cancel: '取消',
  Save: '保存',
  'Assistant is working': '助手正在执行',
  'Search threads': '搜索会话',
  'Loading threads': '正在读取会话',
  'Rename thread': '重命名会话',
  'New Thread': '新建会话',
  'New Chat': '新会话',
  'No threads found': '没有匹配的会话',
  Today: '今天',
  Yesterday: '昨天',
  Earlier: '更早',
  Running: '执行中',
  'More options': '更多选项',
  Rename: '重命名',
  Archive: '归档',
  Delete: '删除',
  'Used tool': '调用工具',
  'Cancelled tool': '已取消的工具',
  Arguments: '参数',
  Result: '结果',
  Allow: '允许本次',
  Deny: '拒绝',
  Answer: '回答',
  Note: '补充说明',
  'Type your answer': '输入回答',
  'Add a note to your decision': '补充你的决定',
  Submit: '提交',
  Confirm: '确认',
  'Select model': '选择模型',
  'Search models...': '搜索模型…',
  'No models found.': '没有匹配的模型',
  Model: '模型',
  'Reasoning effort': '思考深度',
  Reasoning: '推理',
  Thinking: '正在思考',
  'Close Assistant': '收起助手',
  'Open Assistant': '打开本地助手',
  'Open local assistant': '打开本地助手',
  'Toggle Sidebar': '切换会话侧栏',
  Sidebar: '会话侧栏',
  'Displays the mobile sidebar.': '选择本地会话。',
  'View Source': '查看源码',
  'Voice input': '语音输入',
  'Start voice input': '开始语音输入',
  'Stop dictation': '停止听写',
  'Stop voice input': '停止语音输入',
  Close: '关闭',
};
// Locale switches remount the official view while the Paseo store and runtime stay alive.
export function ui(text: string): string {
  return typeof document !== 'undefined' && document.documentElement.lang.startsWith('zh')
    ? (chinese[text] ?? text)
    : text;
}
